import { Farm } from './types';

export const FARMS: Farm[] = [
  {
    id: 'f1',
    name: "Agrichecco / Agriturismo La Piolsa",
    address: "Località Pinedo 50, Claut",
    description: "Ospitalità agrituristica e produzione di formaggi ovini in Malga. Un'esperienza autentica nelle Dolomiti Friulane. Tel: 351 948 4165",
    logo: "https://picsum.photos/seed/agrichecco/100/100",
    owners: [{ name: "Famiglia", role: "Proprietari", photoUrl: "https://picsum.photos/seed/owner1/200/200" }],
    products: [{ name: "Formaggi Ovini", category: "Cheese" }, { name: "Ricotta", category: "Cheese" }],
    specialty: "Formaggi di Malga",
    lat: 46.2676,
    lng: 12.5147,
    connections: ['f27', 'f12', 'f9']
  },
  {
    id: 'f3',
    name: "Agriturismo Al Faggio",
    address: "Via Palotta, Cordenons",
    description: "Ristorazione agrituristica con ortaggi e frutta di stagione biologici. Tel: 339 174 2380",
    logo: "https://picsum.photos/seed/faggio/100/100",
    owners: [{ name: "Titolare", role: "Agricoltore", photoUrl: "https://picsum.photos/seed/owner3/200/200" }],
    products: [{ name: "Ortaggi Bio", category: "Vegetable" }, { name: "Frutta Stagionale", category: "Vegetable" }],
    specialty: "Cucina biologica",
    lat: 45.9819,
    lng: 12.7067,
    connections: ['f10', 'f15', 'f1']
  },
  {
    id: 'f4',
    name: "Azienda agricola Carso di Aila Quadracci",
    address: "Località Aurisina Cave 55, Duino Aurisina",
    description: "Agricampeggio, ortaggi freschi stagionali, olio EVO, miele del Carso, sottoli, confetture. Tel: 339 547 2401",
    logo: "https://picsum.photos/seed/carso/100/100",
    owners: [{ name: "Aila Quadracci", role: "Titolare", photoUrl: "https://picsum.photos/seed/aila/200/200" }],
    products: [{ name: "Olio EVO", category: "Oil" }, { name: "Miele del Carso", category: "Honey" }, { name: "Sottoli", category: "Vegetable" }],
    specialty: "Prodotti del Carso",
    lat: 45.7725,
    lng: 13.6067,
    connections: ['f26', 'f6', 'f8']
  },
  {
    id: 'f5',
    name: "Azienda Agricola Picjemanis",
    address: "Via Campo 137, Gemona del Friuli",
    description: "Vendita diretta di ortaggi di stagione e frutta, vino, fiori e piante. Tel: 388 1995157",
    logo: "https://picsum.photos/seed/picjemanis/100/100",
    owners: [{ name: "Mirela", role: "Responsabile", photoUrl: "https://picsum.photos/seed/mirela/200/200" }],
    products: [{ name: "Ortaggi", category: "Vegetable" }, { name: "Vino", category: "Wine" }, { name: "Fiori", category: "Vegetable" }],
    specialty: "Vendita diretta",
    lat: 46.2753,
    lng: 13.1378,
    connections: ['f11', 'f12', 'f17']
  },
  {
    id: 'f6',
    name: "Azienda agricola Grappolo d'Oro",
    address: "Strada di Sant' Anna 14, Cividale del Friuli",
    description: "Agriristoro e vendita diretta VINI ed olio EVO nel cuore dei Colli Orientali del Friuli. Tel: 0432 716034",
    logo: "https://picsum.photos/seed/grappolo/100/100",
    owners: [{ name: "Famiglia", role: "Vignaioli", photoUrl: "https://picsum.photos/seed/owner6/200/200" }],
    products: [{ name: "Vini COF", category: "Wine" }, { name: "Olio EVO", category: "Oil" }],
    specialty: "Vini dei Colli Orientali",
    lat: 46.0944,
    lng: 13.4333,
    connections: ['f4', 'f8', 'f11']
  },
  {
    id: 'f8',
    name: "Azienda agricola In Cortile di Stefano Calligaris",
    address: "Via Giuseppe Bertolissi 60, Palmanova",
    description: "Vendita diretta di ortaggi di stagione, frutta, vino, fiori e piante. Tel: 0434 781866",
    logo: "https://picsum.photos/seed/incortile/100/100",
    owners: [{ name: "Stefano Calligaris", role: "Titolare", photoUrl: "https://picsum.photos/seed/stefano/200/200" }],
    products: [{ name: "Ortaggi", category: "Vegetable" }, { name: "Vino", category: "Wine" }],
    specialty: "Ortaggi a km0",
    lat: 45.9064,
    lng: 13.3106,
    connections: ['f6', 'f19', 'f13']
  },
  {
    id: 'f7',
    name: "Benedetti Franco e Fabio",
    address: "Via G. Marconi 23 Sottoselva, Sacile",
    description: "Salumi ed insaccati da animali allevati all'aperto - filiera corta. Tel: 0432 924191",
    logo: "https://picsum.photos/seed/benedetti/100/100",
    owners: [{ name: "Franco e Fabio", role: "Allevatori", photoUrl: "https://picsum.photos/seed/franco/200/200" }],
    products: [{ name: "Salumi", category: "Meat" }, { name: "Insaccati", category: "Meat" }],
    specialty: "Filiera corta",
    lat: 45.9536,
    lng: 12.5028,
    connections: ['f15', 'f3', 'f10']
  },
  {
    id: 'f9',
    name: "Bioapicoltura Pura",
    address: "Località Pura 1/A, Lauco",
    description: "Produzione di Miele biologico in ambiente incontaminato. Tel: 338 1646743",
    logo: "https://picsum.photos/seed/pura/100/100",
    owners: [{ name: "Apicoltore", role: "Produttore", photoUrl: "https://picsum.photos/seed/api/200/200" }],
    products: [{ name: "Miele Bio", category: "Honey" }],
    specialty: "Miele di montagna",
    lat: 46.4233,
    lng: 12.9347,
    connections: ['f17', 'f12', 'f22']
  },
  {
    id: 'f11',
    name: "Borgo Romanzo di Casasola Michele",
    address: "Via Ramandolo 7, Nimis",
    description: "Azienda vitivinicola con agriristoro e ristorazione agrituristica e vendita diretta. Tel: 353 4747558",
    logo: "https://picsum.photos/seed/romanzo/100/100",
    owners: [{ name: "Michele Casasola", role: "Vignaiolo", photoUrl: "https://picsum.photos/seed/michele/200/200" }],
    products: [{ name: "Ramandolo DOCG", category: "Wine" }, { name: "Vini Autoctoni", category: "Wine" }],
    specialty: "Vini dolci e ospitalità",
    lat: 46.1994,
    lng: 13.2667,
    connections: ['f6', 'f5', 'f25']
  },
  {
    id: 'f12',
    name: "De Prato Agnese",
    address: "Via Francui 5, Tolmezzo",
    description: "Agriturismo ristorazione, agripub, agribirreria. Tel: 340 538 1558",
    logo: "https://picsum.photos/seed/deprato/100/100",
    owners: [{ name: "Agnese De Prato", role: "Titolare", photoUrl: "https://picsum.photos/seed/agnese/200/200" }],
    products: [{ name: "Birra Agricola", category: "Wine" }, { name: "Piatti Tipici", category: "Meat" }],
    specialty: "Agribirreria",
    lat: 46.4053,
    lng: 13.0186,
    connections: ['f9', 'f17', 'f22']
  },
  {
    id: 'f13',
    name: "Full Moon di Sirianni Althea",
    address: "Via Venezia 132A, Codroipo",
    description: "Vendita diretta ortaggi biologici freschi, agrodolci, carne fresca di polli allevati all'aperto. Tel: 345 2583644",
    logo: "https://picsum.photos/seed/fullmoon/100/100",
    owners: [{ name: "Althea Sirianni", role: "Titolare", photoUrl: "https://picsum.photos/seed/althea/200/200" }],
    products: [{ name: "Pollo ruspante", category: "Meat" }, { name: "Agrodolci", category: "Vegetable" }, { name: "Ortaggi Bio", category: "Vegetable" }],
    specialty: "Avicoltura all'aperto",
    lat: 45.9619,
    lng: 12.9781,
    connections: ['f19', 'f14', 'f8']
  },
  {
    id: 'f14',
    name: "Gli ori del Battilana",
    address: "San Martino al Tagliamento",
    description: "Coltivazione di piccoli frutti stagionali. Tel: 345 122 3970",
    logo: "https://picsum.photos/seed/battilana/100/100",
    owners: [{ name: "Davide Carbone", role: "Produttore", photoUrl: "https://picsum.photos/seed/davide/200/200" }],
    products: [{ name: "Lamponi", category: "Vegetable" }, { name: "Mirtilli", category: "Vegetable" }],
    specialty: "Piccoli frutti",
    lat: 46.0167,
    lng: 12.8667,
    connections: ['f13', 'f21', 'f3']
  },
  {
    id: 'f15',
    name: "I Ciliegi",
    address: "Via Vincenzo Bellini 127, Fontanafredda",
    description: "Vendita diretta Ortaggi e frutta biologici di stagione, agrodolci, sottoli, marmellate. Fattoria didattica. Tel: 340 063 2885",
    logo: "https://picsum.photos/seed/ciliegi/100/100",
    owners: [{ name: "Valentina", role: "Responsabile", photoUrl: "https://picsum.photos/seed/valentina/200/200" }],
    products: [{ name: "Confetture", category: "Vegetable" }, { name: "Sottoli", category: "Vegetable" }],
    specialty: "Trasformati vegetali",
    lat: 45.9722,
    lng: 12.5694,
    connections: ['f3', 'f7', 'f20']
  },
  {
    id: 'f16',
    name: "La Resiana",
    address: "Via Varcota 11, Resia",
    description: "Miele della Val di Resia, aglio di Resia (Presidio Slow Food) e i suoi trasformati in agrodolce. Tel: 349 306 0139",
    logo: "https://picsum.photos/seed/resiana/100/100",
    owners: [{ name: "Michael", role: "Produttore", photoUrl: "https://picsum.photos/seed/michael/200/200" }],
    products: [{ name: "Aglio di Resia", category: "Vegetable" }, { name: "Miele", category: "Honey" }],
    specialty: "Aglio di Resia",
    lat: 46.3744,
    lng: 13.3033,
    connections: ['f5', 'f9', 'f11']
  },
  {
    id: 'f17',
    name: "Azienda agricola La Sisile",
    address: "Via Sot las Vies 5, Villa Santina",
    description: "Ortaggi freschi di stagione biologici freschi e trasformati. Tel: 345 333 6048",
    logo: "https://picsum.photos/seed/sisile/100/100",
    owners: [{ name: "Titolare", role: "Agricoltore", photoUrl: "https://picsum.photos/seed/sisile_owner/200/200" }],
    products: [{ name: "Ortaggi", category: "Vegetable" }, { name: "Trasformati", category: "Vegetable" }],
    specialty: "Ortaggi di montagna",
    lat: 46.4144,
    lng: 12.9214,
    connections: ['f9', 'f12', 'f18']
  },
  {
    id: 'f18',
    name: "L'Allegra Fattoria",
    address: "Caneva, Via Verzegnis 22, Tolmezzo",
    description: "Ristorazione agrituristica, agricampeggio, fattoria didattica, prodotti agrodolci, miele, succo di mela. Tel: 349 452 1694",
    logo: "https://picsum.photos/seed/allegra/100/100",
    owners: [{ name: "Romina", role: "Titolare", photoUrl: "https://picsum.photos/seed/romina/200/200" }],
    products: [{ name: "Succo di Mela", category: "Vegetable" }, { name: "Miele", category: "Honey" }, { name: "Mostarde", category: "Vegetable" }],
    specialty: "Fattoria Didattica",
    lat: 46.3889,
    lng: 12.9917,
    connections: ['f12', 'f17', 'f5']
  },
  {
    id: 'f19',
    name: "Le Fornaci del Zarnic",
    address: "Via F. Baracca 10, Flambruzzo",
    description: "Ristorazione agrituristica, fattoria didattica, succo di mela, marmellate. Tel: 0432 773635",
    logo: "https://picsum.photos/seed/fornaci/100/100",
    owners: [{ name: "Fam. Zarnic", role: "Gestori", photoUrl: "https://picsum.photos/seed/zarnic/200/200" }],
    products: [{ name: "Succo di Mela", category: "Vegetable" }, { name: "Marmellate", category: "Vegetable" }],
    specialty: "Agriturismo per famiglie",
    lat: 45.8833,
    lng: 13.0764,
    connections: ['f13', 'f8', 'f15']
  },
  {
    id: 'f20',
    name: "Luppolo Verde di Polcenigo",
    address: "Via Pordenone 51, Budoia",
    description: "Produttore di birre con ristorazione agrituristica Rifugio città di Vittorio Veneto. Tel: 349 368 0586",
    logo: "https://picsum.photos/seed/luppolo/100/100",
    owners: [{ name: "Birraio", role: "Produttore", photoUrl: "https://picsum.photos/seed/brewer/200/200" }],
    products: [{ name: "Birra Artigianale", category: "Wine" }],
    specialty: "Birra di Polcenigo",
    lat: 46.0428,
    lng: 12.5361,
    connections: ['f24', 'f15', 'f3']
  },
  {
    id: 'f21',
    name: "Caj la chiocciola del Tagliamento",
    address: "San Martino al Tagliamento",
    description: "Allevamento di chiocciole e prodotti derivati. (Dati integrati)",
    logo: "https://picsum.photos/seed/caj/100/100",
    owners: [{ name: "Mattia Marinello", role: "Allevatore", photoUrl: "https://picsum.photos/seed/mattia/200/200" }],
    products: [{ name: "Chiocciole", category: "Meat" }, { name: "Cosmetici Bava", category: "Oil" }],
    specialty: "Elicicoltura",
    lat: 46.0167,
    lng: 12.8667,
    connections: ['f14', 'f13', 'f19']
  },
  {
    id: 'f22',
    name: "Molinari Fabio",
    address: "Località Dietro Piante 14, Zuglio",
    description: "Formaggi stagionati, caciotte, ricotta classica o affumicata, yogurt. Fattoria didattica. Tel: 348 120 7488",
    logo: "https://picsum.photos/seed/molinari/100/100",
    owners: [{ name: "Sarah", role: "Contatto", photoUrl: "https://picsum.photos/seed/sarah/200/200" }],
    products: [{ name: "Formaggi Speziati", category: "Cheese" }, { name: "Ricotta Affumicata", category: "Cheese" }],
    specialty: "Latticini di Carnia",
    lat: 46.4611,
    lng: 13.0258,
    connections: ['f12', 'f17', 'f9']
  },
  {
    id: 'f23',
    name: "Punto Bio",
    address: "Tarcento",
    description: "Azienda agricola biologica. (Dettagli in aggiornamento)",
    logo: "https://picsum.photos/seed/puntobio/100/100",
    owners: [{ name: "Gestore", role: "Agricoltore", photoUrl: "https://picsum.photos/seed/bio/200/200" }],
    products: [{ name: "Ortaggi Bio", category: "Vegetable" }],
    specialty: "Agricoltura Biologica",
    lat: 46.2167,
    lng: 13.2167,
    connections: ['f11', 'f5', 'f16']
  },
  {
    id: 'f24',
    name: "Re Caprone",
    address: "Polcenigo",
    description: "Allevamento caprino e produzione di formaggi di capra.",
    logo: "https://picsum.photos/seed/recaprone/100/100",
    owners: [{ name: "Allevatore", role: "Titolare", photoUrl: "https://picsum.photos/seed/capra/200/200" }],
    products: [{ name: "Formaggio di Capra", category: "Cheese" }, { name: "Latte di Capra", category: "Cheese" }],
    specialty: "Caprino",
    lat: 46.0294,
    lng: 12.5000,
    connections: ['f20', 'f15', 'f7']
  },
  {
    id: 'f25',
    name: "Villa Beria (ex Roi Clàr)",
    address: "Via F. di Manzano 1, Manzano",
    description: "Azienda vitivinicola con affinamento vini in anfora di ceramica, degustazioni.",
    logo: "https://picsum.photos/seed/beria/100/100",
    owners: [{ name: "Famiglia", role: "Vignaioli", photoUrl: "https://picsum.photos/seed/beria_own/200/200" }],
    products: [{ name: "Vino in Anfora", category: "Wine" }],
    specialty: "Vini in anfora",
    lat: 45.9897,
    lng: 13.3778,
    connections: ['f11', 'f6', 'f8']
  },
  {
    id: 'f26',
    name: "Tenuta Mivea",
    address: "Via dei F.lli Rusjan 66, Savogna d'Isonzo",
    description: "Ortaggi freschi di stagione, agrodolci, mostarde, Brovada Dop. Fattoria didattica.",
    logo: "https://picsum.photos/seed/mivea/100/100",
    owners: [{ name: "Famiglia", role: "Gestori", photoUrl: "https://picsum.photos/seed/mivea_own/200/200" }],
    products: [{ name: "Brovada DOP", category: "Vegetable" }, { name: "Mostarde", category: "Vegetable" }],
    specialty: "Brovada DOP",
    lat: 45.9031,
    lng: 13.5681,
    connections: ['f4', 'f6', 'f25']
  },
  {
    id: 'f27',
    name: "Val dei Perons di Fabbro Joshua",
    address: "Claut",
    description: "Azienda agricola in Valcellina. Produzioni locali.",
    logo: "https://picsum.photos/seed/perons/100/100",
    owners: [{ name: "Joshua Fabbro", role: "Titolare", photoUrl: "https://picsum.photos/seed/joshua/200/200" }],
    products: [{ name: "Prodotti Montagna", category: "Cheese" }],
    specialty: "Agricoltura eroica",
    lat: 46.2690,
    lng: 12.5200,
    connections: ['f1', 'f12']
  },
  {
    id: 'f2',
    name: "Ai Bassi",
    address: "Fiume Veneto",
    description: "Azienda agricola locale. Produzioni stagionali.",
    logo: "https://picsum.photos/seed/aibassi/100/100",
    owners: [{ name: "Agricoltore", role: "Proprietario", photoUrl: "https://picsum.photos/seed/bassi/200/200" }],
    products: [{ name: "Colture estensive", category: "Vegetable" }],
    specialty: "Seminativi",
    lat: 45.9286,
    lng: 12.7303,
    connections: ['f10', 'f3']
  },
  {
    id: 'f10',
    name: "Borgo Decimo",
    address: "Azzano Decimo",
    description: "Realtà agricola nel cuore di Azzano Decimo.",
    logo: "https://picsum.photos/seed/borgodecimo/100/100",
    owners: [{ name: "Gestore", role: "Proprietario", photoUrl: "https://picsum.photos/seed/decimo/200/200" }],
    products: [{ name: "Vino", category: "Wine" }],
    specialty: "Viticoltura",
    lat: 45.8858,
    lng: 12.7119,
    connections: ['f2', 'f3', 'f7']
  }
];